apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      service: recommender
  template:
    metadata:
      labels:
        service: recommender
    spec:
      containers:
        - image: {{ .Values.images.recommender | default "recommender" }}
          name: recommender
          ports:
            - name: rest
              containerPort: 3001
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
