apiVersion: v1
kind: Service
metadata:
  labels:
    service: recommender-rest
  name: recommender-rest
spec:
  type: NodePort
  ports:
    - name: rest
      port: 3001
      protocol: TCP
      targetPort: rest
  selector:
    service: recommender-rest
status:
  loadBalancer: {}
