apiVersion: v1
kind: Service
metadata:
  labels:
    service: recommender-grpc
  name: recommender-grpc
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: grpc
  selector:
    service: recommender-grpc
status:
  loadBalancer: {}
