/**
 * loopback4-example-shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse200Headers } from './inline-response200-headers';


export interface InlineResponse200 { 
    greeting?: string;
    date?: string;
    url?: string;
    headers?: InlineResponse200Headers;
}

