/**
 * loopback4-example-shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoopbackPingResponseHeaders } from './loopback-ping-response-headers';


export interface LoopbackPingResponse { 
    greeting?: string;
    date?: string;
    url?: string;
    headers?: LoopbackPingResponseHeaders;
}

