apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: recommender-image
spec:
  output:
    to:
      kind: ImageStreamTag
      name: recommender:latest
  source:
    images:
    - from:
        kind: ImageStreamTag
        name: shopping-base:latest
      paths:
      - destinationDir: base
        sourcePath: /home/node/app/.
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:12
        namespace: openshift
      dockerfilePath: base/openshift/Dockerfile.recommender
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
  - imageChange:
      from:
        kind: "ImageStreamTag"
        name: "shopping-base:latest"
    type: ImageChange
